language: python
dist: xenial
addons:
    postgresql: "10"
    apt:
        packages:
            - "postgresql-10-postgis-2.4"
sudo: false
python:
    - "3.6"
    - "3.7"
    - "3.8"
env:
  - DATABASE_URL="postgis://test:test@localhost/test"
install: 
    - pip install poetry
    - poetry install
    - npm ci
    - npm run build
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
    - psql -c "CREATE DATABASE test;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
script: 
    - poetry run pytest --ds=openstates.test_settings --reuse-db -v geo graphapi public v1 utils
    - poetry run flake8
notifications:
    email:
        - james@openstates.org
