language: python
dist: xenial
addons:
    postgresql: "10"
    apt:
        packages:
            - "postgresql-10-postgis-2.4"
sudo: false
python:
    - "3.6"
env:
  - DATABASE_URL="postgis://test:test@localhost/test"
install: 
    - pip install pipenv
    - pipenv install --dev
    - npm install
    - npm run build
    - pipenv graph
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
    - psql -c "CREATE DATABASE test;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
script: 
    - pipenv run pytest --ds=openstates.test_settings --reuse-db -v geo graphapi public v1 utils
    - pipenv run flake8
notifications:
    email:
        - james@openstates.org
