language: python
python:
    - "3.5"
    - "3.6"
install: 
    - pip install -rrequirements.txt
script: 
    - pytest --ds=openstates.settings --reuse-db -v
    - flake8
notifications:
    email:
        - james@openstates.org
