language: python
addons:
    postgresql: "9.4"
    apt:
        packages:
            - "postgresql-9.4-postgis-2.3"
python:
    - "3.5"
    - "3.6"
install: 
    - pip install -r requirements.txt
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
    - psql -c "CREATE DATABASE test;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
script: 
    - pytest --ds=openstates.settings --reuse-db -v
    - flake8
notifications:
    email:
        - james@openstates.org
