language: python
addons:
    postgresql: "9.4"
    apt:
        packages:
            - "postgresql-9.4-postgis-2.3"
python:
    - "3.6"
env:
  - DATABASE_URL="postgis://test:test@localhost/test"
install: 
    - pip install pipenv
    - pipenv install --dev
    - pipenv graph
before_script:
    - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
    - psql -c "CREATE DATABASE test;" -U postgres
    - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
script: 
    - pipenv run pytest --ds=openstates.settings --reuse-db -v
    - pipenv run flake8
notifications:
    email:
        - james@openstates.org
