language: python
addons:
    postgresql: "9.4"
    apt:
        packages:
            - "postgresql-9.4-postgis-2.3"
python:
    - "3.5"
    - "3.6"
install: 
    - pip install -rrequirements.txt
script: 
    - pytest --ds=openstates.settings --reuse-db -v
    - flake8
notifications:
    email:
        - james@openstates.org
