version: "3.4"

volumes:
  openstates-postgres:
    name: openstates-postgres

services:
  db:
    image: "mdillon/postgis:11-alpine"
    hostname: "db"
    ports:
      - "5405:5432"
    environment:
      POSTGRES_PASSWORD: openstates
      POSTGRES_USER: openstates
      POSTGRES_DB: openstatesorg
    volumes:
      - openstates-postgres:/var/lib/postgresql/data
  # webpack:
  #   build: .
  #   command: ./docker/webpack-start.sh
  #   volumes:
  #     - .:/code

  django:
    build: .
    # entrypoint: /venv/bin/poetry run ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL
