version: "3.5"

networks:
  openstates-network:
      name: openstates-network

volumes:
  openstates-postgres:
    name: openstates-postgres

services:
  db:
    image: "mdillon/postgis:11-alpine"
    hostname: "db"
    ports:
      - "5405:5432"
    environment:
      POSTGRES_PASSWORD: openstates
      POSTGRES_USER: openstates
      POSTGRES_DB: openstatesorg
    volumes:
      - openstates-postgres:/var/lib/postgresql/data
    networks:
      - openstates-network

  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY
      - CACHE_URL
    depends_on:
      - db
    networks:
      - openstates-network

  # webpack:
  #   build: .
  #   command: ./docker/webpack-start.sh
  #   volumes:
  #     - .:/code
